Repository codebar/planner, pull requests merged in 2022-10, with the labels that each got.

#1819 New banner image and added another button
  app/assets/images/uncodebar-group.jpeg
  app/assets/stylesheets/partials/_hero.scss
  app/views/dashboard/show.html.haml
  app/views/layouts/_navigation.html.haml
Labels: hacktoberfest, hacktoberfest-accepted

#1802 chore(1797): Invite everyone
  .gitignore
  .rubocop.yml
  app/mailers/event_invitation_mailer.rb
  app/views/event_invitation_mailer/invite_coach.html.haml
  db/schema.rb
  spec/mailers/event_invitation_mailer_spec.rb
Labels: enhancement

#1799 feat(1746): filter sponsors by chapter
  app/controllers/admin/sponsors_controller.rb
  app/models/sponsors_search.rb
  app/views/admin/sponsors/index.html.haml
  spec/features/admin/sponsor_spec.rb
  spec/models/sponsors_search_spec.rb
Labels: feature

#1798 feat(1765): remote events
  app/assets/stylesheets/partials/_layout.scss
  app/controllers/admin/events_controller.rb
  app/controllers/application_controller.rb
  app/controllers/events_controller.rb
  app/controllers/invitations_controller.rb
  app/helpers/event_helper.rb
  app/mailers/event_invitation_mailer.rb
  app/models/event.rb
  app/views/admin/events/_form.html.haml
  app/views/admin/events/edit.html.haml
  app/views/admin/events/show.html.haml
  app/views/event_invitation_mailer/attending.html.haml
  app/views/event_invitation_mailer/invite_coach.html.haml
  app/views/event_invitation_mailer/invite_student.html.haml
  app/views/events/show.html.haml
  app/views/invitations/show.html.haml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/en_AU.yml
  config/locales/en_GB.yml
  config/locales/en_US.yml
  config/locales/es.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/no.yml
  db/migrate/20220820180050_add_virtual_to_events.rb
  db/schema.rb
  spec/features/admin/event_spec.rb
Labels: feature
